version: "3"

networks:
  proxy-net:
    external: true

services:
  excalidraw:
    image: excalidraw/excalidraw:latest
    container_name: excalidraw
    restart: unless-stopped
    expose:
      - 80
    networks:
      - proxy-net
