version: "3"

volumes:
  caddy:
  headscale:

services:
  caddy:
    image: "caddy"
    container_name: "caddy"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy:/data
      - ./Caddyfile:/etc/caddy/Caddyfile

  headscale:
    image: "headscale/headscale"
    container_name: "headscale"
    command: serve
    restart: unless-stopped
    volumes:
      - headscale:/var/lib/headscale
      - ./config.yaml:/etc/headscale/config.yaml
