version: "3"

networks:
  proxy-net:
    external: true

services:
  stirling-pdf:
    image: "frooodle/s-pdf:latest"
    container_name: "stirling-pdf"
    restart: unless-stopped
    expose:
      - 8080
    networks:
      - proxy-net
