version: "3"

networks:
  proxy-net:
    external: true

services:
  librespeed:
    image: ghcr.io/librespeed/speedtest:latest
    container_name: librespeed
    restart: unless-stopped
    networks:
      - proxy-net
    expose:
      - 8080
    environment:
      MODE: standalone
      TITLE: "LibreSpeed"
