version: "3"

networks:
  proxy-net:
    external: true

services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Remove the following line if you don't need user sign in
      - ./users.yml:/data/users.yml
    networks:
      - proxy-net
    expose:
      - 8080
    environment:
      DOZZLE_NO_ANALYTICS: true
      # Remove the following line if you don't need user sign in
      DOZZLE_AUTH_PROVIDER: simple
